# Generated by Django 2.0.6 on 2018-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_photo_uploadfilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='blog/profile_pic')),
                ('photo', models.ImageField(blank=True, upload_to='blog/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
